apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: userpanel-auto-scaler
spec:
  minReplicas: 1
  maxReplicas: 4

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userpanel
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: auth-auto-scaler
# spec:
#   minReplicas: 1
#   maxReplicas: 2

#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: auth
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
# ---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: coursemanage-auto-scaler
# spec:
#   minReplicas: 1
#   maxReplicas: 2

#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: coursemanage
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
# ---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: courseselection-auto-scaler
# spec:
#   minReplicas: 1
#   maxReplicas: 2

#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: courseselection
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50